### Numpy Assignment

In [2]:
import numpy as np

#### `1. What is a Python library? Why do we use Python libraries?`

Ans  :
    
    python library is collection of related module.it contain bunddles of code that we can use repeatedly.
    
    Python libraries make it easier for developers to work on specific tasks without reinventing the wheel. They provide a wide range of tools and modules for various tasks. 

#### `2. What is the difference between Numpy array and List?`

Ans :
    
    Numpy Array :- numpy array contain no of element have same data type. 
                    array should be homogeneous.
                    it consume less memory
                    we can define array by using numpy library. (import numpy as np)
                    Ex. np.array([1,2,3,4,5]) like that
                    
    List :  list is used to store the multiple iteam in single variable. list is unorder, mutable,
            its allow duplicate elements.
            
            list contain numbers of element having differant data type. 
            list is hetergenous data structure.
            list consume more memory as compare to array.
            
            Implementation of list is l = [1,2,3,4,5,6] like that

#### `3. Fin^ the shape, size and dimension of the following array?`


[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
arr =[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [4]:
import numpy as np
arr = np.array(arr)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
# shape of array 
print(arr.shape)

(3, 4)


In [6]:
#Size of array
print(arr.size)

12


In [7]:
# n dimension of array
print(arr.ndim)

2


#### `4. Write python code to access the first row of the following array?`


[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [8]:
arr =[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [9]:
import numpy as np 
arr =np.array(arr)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
# Access the first row of array
arr[0]

array([1, 2, 3, 4])

#### `5. How do you access the element at the third row and fourth column from the given numpy array?`

In [11]:
arr =[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [12]:
arr =np.array(arr)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
arr[2,[3]]

array([12])

#### `6. Write code to extract all odd-indexed elements from the given numpy array?`

In [105]:
import numpy as np
arr =np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [116]:
# Extract odd indexed from array
odd_elements = arr[:, ::2]
print(odd_elements)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


#### `7. How can you generate a random 3x3 matrix with values between 0 and 1?`

In [16]:
import numpy as np
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
arr1 =np.ones((3,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### `8. Describe the difference between np.random.rand and np.random.randn?`

In [18]:
import numpy as np
np.random.rand(3,4)

array([[0.12045544, 0.59378921, 0.70636069, 0.21198192],
       [0.00116992, 0.0040617 , 0.53836045, 0.88233025],
       [0.76359279, 0.83662522, 0.49308815, 0.71799429]])

##### its gives random values from given shape 

In [19]:
np.random.randn(3,4)

array([[ 0.12523743,  0.29484031, -1.15006889,  1.09706343],
       [ 0.50443773,  0.46197353,  0.70824776,  0.23002993],
       [-1.34064287,  0.39526269,  0.12653332,  0.02361195]])

##### Return a sample (or samples) from the "standard normal" distribution.

#### `9. Write code to increase the dimension of the following array?`

In [20]:
# By using Expand dimension we can increase the dimesion of array

In [21]:
arr =[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [22]:
arr =np.array(arr)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr1 =np.expand_dims(arr,axis =0)

In [24]:
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [25]:
arr2 =np.expand_dims(arr,axis=1)

In [26]:
arr2

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

#### `10. How to transpose the following array in NumPy?`

In [27]:
arr =[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [29]:
import numpy as np
arr =np.array(arr)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

#### `11. Consider the following matrix:`

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [88]:
import numpy as np
MatrixA2 = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
MatrixB2 = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [89]:
MatrixA =np.array(MatrixA2)
MatrixA

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
MatrixB =np.array(MatrixB2)
MatrixB

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Perform the following operation using Python

Perform Index wise Multiplication

In [91]:
MatrixA * MatrixB

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

Matrix multiplication

In [92]:
Matrix = MatrixA.T
Matrix @ MatrixB

array([[107, 122, 137, 152],
       [122, 140, 158, 176],
       [137, 158, 179, 200],
       [152, 176, 200, 224]])

Add both matrix

In [93]:
MatrixA + MatrixB

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

Subtract B Matrix from MatrixA

In [94]:
MatrixB - MatrixA

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Devide B2 Matrix from Matrix A2

In [95]:
MatrixB / MatrixA

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### `12.  Which function in Numpy can be used to swap the byte order of an array?`

Ans :


     Byteswap function is use to swap byte order of an array

In [96]:
# Example
import numpy as np
arr =np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [97]:
arr.byteswap(inplace = True)

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744])

#### `13.  What is the significance of the np.linalg.inv function?`

Ans :
    
    We use numpy. linalg. inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix

#### `14. What does the np.reshape function do, and how is it use^?`

Ans :
    
     it gives new shape to the array without changing its data.

In [101]:
# example
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### `15. What is broadcasting in Numpy?`

Ans :


     The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.
    